config/routes.rb
Rails.application.routes.draw do
  get 'requests/new'

  get 'offices/new'

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  # ログイン
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get 'attend_employees'
      get 'attendances/one_month_apply'
      patch 'attendances/update_one_month_apply'
      patch 'attendances/confirmation_one_month_apply'
      get 'attendances/edit_overtime_work_apply'
      patch 'attendances/update_overtime_work_apply'
      get 'attendances/recive_overtime_work_apply'
      patch 'attendances/confirmation_overtime_work_apply'
      get 'attendances/recive_change_attendance_apply'
      patch 'attendances/confirmation_change_attendance_apply'
      get 'attendances/edit_log'
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
    end
    collection do
      post 'import'
      resources :offices
    end
    resources :attendances, only: :update
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :affiliation, length: { in: 2..30 }, allow_blank: true
  validates :basic_work_time, presence: true
  validates :work_time, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  def User.digest(string)
    cost =
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def self.search(search)
    return User.all unless search
    User.where(['name LIKE ?', "%#{search}%"])
  end
  
  def self.import(file)
    imported_num = 0

    open(file.path, 'r:cp932:utf-8', undef: :replace) do |f|
      csv = CSV.new(f, :headers => :first_row)
      begin
        csv.each do |row|
          next if row.header_row?
          table = Hash[[row.headers, row.fields].transpose]

          user = find_by(email: table["email"])
          if user.nil?
            user = new
          end

          user.attributes = table.to_hash.slice(*table.to_hash.except(:email, :created_at, :updated_at).keys)

          if user.valid?
            user.save!
            imported_num += 1
          end
        end
      rescue
      end
    end
    imported_num
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i(show edit update destroy attend_employees edit_basic_info)
  before_action :logged_in_user, only: %i(index show edit update destroy attend_employees edit_basic_info import)
  before_action :admin_user, only: %i(index destroy attend_employees edit_basic_info)
  before_action :correct_or_superior_user, only: %i(show)
  before_action :admin_exclusion, only: %i(show)
  before_action :set_one_month, only: %i(show attend_employees)

  def index
    if params[:search] == ""
      redirect_to users_url
      flash[:danger] = "キーワードを入力してください。"
    else
      @users = User.paginate(page: params[:page]).search(params[:search]).order(id: "ASC").where.not(admin: true)
      if params[:search].present?
        flash.now[:success] = "検索結果:#{@users.count}件"
      end
    end
  end
  
  def import
    if params[:csv_file].blank?
      flash[:danger] = "インポートするCSVファイルを選択してください。"
      redirect_to users_url
    else
      num = User.import(params[:csv_file])
      if num > 0
        flash[:success] = "#{num.to_s}件のユーザー情報を追加/更新しました。"
        redirect_to users_url
      else
        flash[:danger] = "読み込みエラーが発生しました。"
        redirect_to users_url
      end
    end
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ユーザーの新規登録に成功しました。"
      redirect_to @user
    else
      render :new
    end
  end
  
  def show
    @worked_sum = @attendances.where.not(started_at: nil).count
    @superiors = superior_without_me
    @superiors_all = superior_add_me
    @month = set_one_month_apply
    
    respond_to do |format|
      format.html
      format.csv do
          send_data render_to_string.encode(Encoding::Windows_31J, undef: :replace, row_sep: "\r\n", force_quotes: true),
          filename: "#{@user.name}(#{l(@first_day, format: :middle)})勤怠情報.csv", type: :csv
      end
    end
  end
  
  def edit
  end
  
  def update
    unless @user.admin?
      if @user.update_attributes(user_params)
        flash[:success] = "#{@user.name}の情報を更新しました。"
        redirect_to users_url
      elsif @user.name.blank?
        flash[:danger] = "更新に失敗しました。<br>" + @user.errors.full_messages.join("<br>")
        redirect_to users_url
      else
        flash[:danger] = "#{@user.name}の更新に失敗しました。<br>" + @user.errors.full_messages.join("<br>")
        redirect_to users_url
      end
    else
      redirect_to users_url
    end
  end
  
  def destroy
    unless @user.admin?
      @user.destroy
      flash[:success] = "#{@user.name}のデータを削除しました。"
      redirect_to users_url
    else
      redirect_to users_url
    end
  end
  
  def attend_employees
    @users = working_users
  end
  
  def edit_basic_info
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :affiliation, :employee_number, :uid, :superior, :admin, :password, :password_confirmation)
    end
    
    def basic_info_params
      params.require(:user).permit(:affiliation, :basic_work_time, :work_time)
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # 勤怠基本情報を指定のフォーマットで返します。  
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>
  
  <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :affiliation, class: "form-control" %>
  
  <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
  <%= f.number_field :employee_number, class: "form-control" %>

  <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :uid, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
  
  <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :basic_work_time, class: "form-control" %>

  <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_start_time, class: "form-control" %>

  <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_end_time, class: "form-control" %>

  <%= f.submit yield(:btn_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/_month_apply_form.html.erb
<% if current_user?(@user) %>
  <%= form_with(model: @user, url: attendances_update_one_month_apply_user_path(date: @first_day), local: true, method: :patch) do |f| %>
    <div class="form-group">
      <% @superiors.each do |superior| %>
        <% @month.each do |month| %>
          <%= fields_for "attendances[]", month do |m| %>
            <% if month.status.blank? %>
              <%= "所属長承認　#{apply_status(month.status)}" %>
            <% else %>
              <%= "所属長承認　#{month.superior_name}#{apply_status(month.status)}" %>
            <% end %>
            <%= m.collection_select :superior_id, @superiors, :id, :name, {include_blank: true, selected: nil}, {class: "form-control"} %>
            <%= m.hidden_field :status, value: "申請中" %>
            <%= m.hidden_field :month_apply, value: @first_day %>
            <%= m.hidden_field :month_approval, value: 2 %>
            <%= m.hidden_field :month_check, value: "0" %>
          <% end %>
          <% break %>
        <% end %>
        <% break %>
      <% end %>
    </div>
    <div>
      <% @attendances.each do |day| %>
        <% if Date.today.at_end_of_month > day.worked_on %>
          <% @month.each do |month| %>
            <%= f.submit "#{apply_btn_status(month.status)}", data: { confirm: "申請情報を提出しますか？" }, class: "btn btn-primary btn-block" %>
          <% break %>
        <% end %>
        <% else %>
          <%= f.submit "申請", class: "btn btn-primary btn-block", disabled: true %>
        <% end %>
        <% break %>
      <% end %>
    </div>
  <% end %>
<% else %>
  <% @month.each do |month| %>
    <% @superiors_all.each do |superior| %>
      <% if month.superior_id == superior.id %>
        <%= "所属長承認　#{month.superior_name}#{apply_status(month.status)}" %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/users/attend_employees.html.erb
<% provide(:title, "出勤社員一覧") %>
<h1>出勤社員一覧</h1>

<% if @users.count == 0 %>
  <h1>現在出社している社員はいません。</h1>
<% else %>
  <table class="table table-condensed table-bordered table-hover" id="attend-table">
    <thead>
      <tr>
        <td>社員番号</td>
        <td>名前</td>
      </tr>
    </thead>
    <tbody>
      <% @users.zip(@attendances) do |user, day| %>
        <tr>
          <td><%= user.employee_number %></td>
          <td><%= user.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %> 

app/views/users/edit.html.erb
<% provide(:title, "ユーザー情報編集") %>
<% provide(:class_text, "user--edit") %>
<% provide(:btn_text, "更新") %>
<h1>ユーザー情報の編集</h1>
<!--< provide(:title, "ユーザー情報編集") %>-->
<!--< provide(:class_text, "user--edit") %>-->
<!--< provide(:btn_text, "更新") %>-->
<!--<h1>ユーザー情報の編集</h1>-->

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>
<!--<div class="row">-->
<!--  <div class="col-md-6 col-md-offset-3">-->
<!--    <= render 'form' %>-->
<!--  </div>-->
<!--</div>-->

app/views/users/edit_basic_info.html.erb
<%= provide(:title, "基本情報の修正") %>
<h1>システム全体の基本情報設定ページ</h1>
<h1>現在未実装</h1>

app/views/users/index.html.erb
<% provide(:title, "ユーザー一覧") %>
<% provide(:class_text, "user--edit") %>
<% provide(:btn_text, "更新") %>
<h1><%= params[:search].present? ? "検索結果" : "ユーザー一覧" %></h1>
<h3 class="center"><%= link_to "戻る", users_path if params[:search].present? %></h3>
<div class="container">
  <div class="row form-group">
    
    <!-- CSVインポートフォーム -->
    <div class="col-md-4 col-md-offset-1 csv-group">
      <%= form_tag(import_users_path, method: :post, multipart: true) do %>
        <%= file_field_tag :csv_file, class: "form-control form-csv" %>
        <%= submit_tag "CSVをインポート", class: "btn btn-primary btn-block btn-csv" %>
      <% end %>
    </div>
    
    <!-- ユーザー検索フォーム -->
    <div class="col-md-2 col-md-offset-2 input-group">
      <p>ユーザー名検索</p>
      <%= form_tag(users_path, method: :get) do %>
        <span class="input-group-btn">
          <%= text_field_tag :search, '', placeholder: 'キーワドを入力', class: "form-control"  %>
          <%= submit_tag '検索', name: :nil, class: "btn btn-primary" %>
        </span>
      <% end %>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-10 col-md-offset-1 paginate-top"><%= will_paginate %></div>
  </div>
  
  <div class="row col-md-10 col-md-offset-1 acd-users">
    <% @users.each do |user| %>
      <div>
        <div>
          <p><%= user.name %></p>
          <p>| 
            <% if current_user.admin? && !current_user?(user) %>
              <%= link_to "削除", user, method: :delete,
                                  data: { confirm: "#{user.name}を削除してよろしいですか？" },
                                  class: "btn btn-primary" %>
            <% end %>
          </p>
        </div>

        <!-- アコーディオン表示 -->
        <div class="acd jumbotron">
          <div class="acd-content col-md-2">
            <a class="btn btn-primary btn-lg btn-edit" data-toggle="collapse" href="#collapse<%= user.id %>" role="button"> <!-- user.idを渡して各ユーザーに紐付け -->
              編集
            </a>
          </div>
        </div>
        <div class="collapse collapse-panel" id="collapse<%= user.id %>"> <!-- user.idを渡して各ユーザーに紐付け -->
          <div class="collapse-body">
            <%= render 'form', { user: user } %> <!-- render partial: 'form', locals: { user: user } でも可。 -->
          </div>
        </div>
      </div>
    <% end %>
  </div>
  
  <div class="row">
    <div class="col-md-10 col-md-offset-1 paginate-bottom"><%= will_paginate %></div>
  </div>
</div>
<!-- モーダルウィドウ -->
<div id="edit_basic_info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit_basic_info" data-toggle="collapse" href="edit_basic_info" role="button" aria-expanded="false" aria-controls="edit_basic_info"></div>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<% provide(:class_text, "signup") %>
<% provide(:btn_text, "新規作成") %>

<h1>ユーザー登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages', object: @user %>

      <%= f.label :name, class: "label-#{yield(:class_text)}" %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email, class: "label-#{yield(:class_text)}" %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
      <%= f.text_field :affiliation, class: "form-control" %>

      <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
      <%= f.number_field :employee_number, class: "form-control" %>

      <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
      <%= f.text_field :uid, class: "form-control" %>

      <%= f.label :password, class: "label-#{yield(:class_text)}" %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
      <%= f.time_field :basic_work_time, class: "form-control" %>

      <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)}" %>
      <%= f.time_field :designated_work_start_time, class: "form-control" %>

      <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)}" %>
      <%= f.time_field :designated_work_end_time, class: "form-control" %>

      <%= f.submit yield(:btn_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name)%>
<div>
  <table class="table table-bordered table-condensed" id="user-table">
    <thead>
      <tr>
        <td>
          <%= link_to "←", user_path(date: @first_day.prev_month), class: "btn btn-primary" if current_user?(@user) %>
          &emsp;<%= l(@first_day, format: :middle) %>&emsp;時間管理表&emsp;
          <%= link_to "→", user_path(date: @first_day.next_month), class: "btn btn-primary" if current_user?(@user) %>
        </td>
        <td>
          指定勤務開始時間&emsp;<%= @user.designated_work_start_time.strftime("%R") %><br>
          指定勤務終了時間&emsp;<%= @user.designated_work_end_time.strftime("%R") %>
        </td>
        <td colspan="3">基本時間&emsp;<%= format_basic_info(@user.basic_work_time) %></td>
        <td>初月&emsp;<%= @first_day.strftime('%m/%d') %></td>
      </tr>
      <tr>
        <td>所属&emsp;<%= @user.affiliation.present? ? @user.affiliation : "未所属" %></td>
        <td>氏名&emsp;<%= @user.name %></td>
        <td>コード</td>
        <td><%= @user.employee_number %></td>
        <td>出勤日数&emsp;<%= @worked_sum %>日</td>
        <td>締め&emsp;<%= @last_day.strftime('%m/%d') %></td>
      </tr>
    </thead>
  </table>
  
  <% if current_user.superior? && current_user?(@user) %>
    <div class="news">
      <p>
        【所属長承認申請のお知らせ】
        <% unless has_month_apply.count == 0 %>
          <%= link_to "通知が#{has_month_apply.count}件あります。",
                      attendances_one_month_apply_user_path(@user), remote: true, class: "notice-superior" %>
        <% end %>
      </p>
      <p>
        【勤怠変更申請のお知らせ】
        <% unless has_change_apply.count == 0 %>
          <%= link_to "通知が#{has_change_apply.count}件あります。",
                       attendances_recive_change_attendance_apply_user_path(date: @first_day), remote: true, class: "notice-superior" %>
        <% end %>
      </p>
      <p>
        【残業申請のお知らせ】
        <% unless has_overtime_apply.count == 0 %>
          <%= link_to "通知が#{has_overtime_apply.count}件あります。",
                      attendances_recive_overtime_work_apply_user_path(@user), remote: true, class: "notice-superior" %>
        <% end %>
      </p>
    </div>
  <% end %>
  
  <div class="btn-user-table">
    <% if current_user?(@user) %>
      <div class="btn-proup">
        <%= link_to "勤怠情報を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-primary" %>
        <%= link_to "CSV出力", user_path(date: @first_day, format: :csv), class: "btn btn-primary" %>
        <%= link_to "勤怠編集ログ(承認済)", attendances_edit_log_user_path(date: @first_day), class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
  
  <table class="table table-bordered table-condensed table-striped" id="user-table">
    <thead>
      <tr>
        <td rowspan="4">残業申請</td>
        <td rowspan="4">日付</td>
        <td rowspan="4">曜日</td>
      </tr>
      <tr>
        <td colspan="8">【実績】</td>
        <td colspan="5">所定外勤務</td>
      </tr>
      <tr>
        <td colspan="3">出社</td>
        <td colspan="3">退社</td>
        <td rowspan="2">在社時間</td>
        <td rowspan="2">備考</td>
        <td colspan="2">終了時間</td>
        <td rowspan="2">時間外時間</td>
        <td rowspan="2">業務処理内容</td>
        <td rowspan="2">指示者確認<%= "\u329e" %></td>
      </tr>
      <tr>
        <td>時</td>
        <td>分</td>
        <td></td>
        <td>時</td>
        <td>分</td>
        <td></td>
        <td>時</td>
        <td>分</td>
      </tr>
    </thead>
    
    <tbody>
      <% @attendances.each do |day| %>
        <tr>
          <td>
            <% if Date.today.at_end_of_month >= day.worked_on %>
              <%= link_to "残業申請", attendances_edit_overtime_work_apply_user_path(date: day.worked_on),
                                        remote: true, class: "btn btn-primary" if current_user?(@user) %>
            <% else %>
              <%= link_to "残業申請", attendances_edit_overtime_work_apply_user_path(date: day.worked_on),
                                        remote: true, class: "btn btn-primary disabled" if current_user?(@user) %>
            <% end %>
          </td>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td>
            <% if day.worked_on.wday == 0 %>
              <font color="#ff000">
            <% elsif day.worked_on.wday == 6 %>
              <font color="#0033cc">
            <% end %>
            <%= $days_of_the_week[day.worked_on.wday] %>
          </td>
          <td><%= day.changed_started_at.hour if day.changed_started_at.present? %></td>
          <td><%= day.changed_started_at.floor_to(15.minutes).strftime("%M") if day.changed_started_at.present? %></td>
          <td>
            <% if btn_text = attendance_attend(day) %>
              <%= link_to "#{btn_text}", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-block btn-attendance" if current_user?(@user) %>
            <% end %>
          </td>
          <td><%= day.changed_finished_at.hour if day.changed_finished_at.present? %></td>
          <td><%= day.changed_finished_at.floor_to(15.minutes).strftime("%M") if day.changed_finished_at.present? %></td>
          <td>
            <% if btn_text = attendance_leave(day) %>
              <%= link_to "#{btn_text}", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-block btn-attendance" if current_user?(@user) %>
            <% end %>
          </td>
          <td>
            <% if day.changed_started_at.present? && day.changed_finished_at.present? %>
              <%= str_times = working_times(day.changed_started_at.floor_to(15.minutes), day.changed_finished_at.floor_to(15.minutes), day.change_next_day_check) %>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td><%= day.note %></td>
          <td><%= day.overtime_end_plan.strftime("%-H") if day.overtime_end_plan.present? %></td>
          <td><%= day.overtime_end_plan.floor_to(15.minutes).strftime("%M") if day.overtime_end_plan.present? %></td>
          <td>
            <%= format("%.2f", day.overtime_hours.to_f.floor_to(0.25)) if day.overtime_end_plan.present? %>
            <% @total_overtime_working = @total_overtime_working.to_f + day.overtime_hours.to_f.floor_to(0.25) %>
          </td>
          <td><%= day.overtime_detail %></td>
          <td>
            <%= day.change_superior_name unless day.change_status == "なし" %><%= change_status_text(day.change_status) %>
            <%= tag.br if day.change_status.present? && day.change_status != "なし" && day.overtime_status.present? %>
            <%= day.overtime_superior_name %><%= overtime_status_text(day.overtime_status) %>
          </td>
        </tr>
      <% end %>
    </tbody>
    
    <tfoot>
      <tr>
        <td></td>
        <td colspan="2"></td>
        <td colspan="6"></td>
        <td><%= format("%.2f", @total_working_times.to_f) %></td>
        <td colspan="3"></td>
        <td><%= format("%.2f", @total_overtime_working) %></td>
        <td></td>
        <td>
          <div class="application-form">
            <%= render 'month_apply_form' %> <!-- 1ヶ月勤怠申請ボタンフォーム -->
          </div>
        </td>
      </tr>
    </tfoot>
  </table>
  <div class="col-md-2 col-md-offset-5 center">
    <%  if current_user.superior? && current_user.id != @user.id %>
      <%= link_to "戻る", user_path(current_user), class: "btn btn-lg btn-block btn-default" %>
    <% end %>
  </div>
</div>
<!-- モーダルウィドウ -->
<div id="one_month_apply" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit_overtime_work_apply" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="recive_overtime_work_apply" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="recive_change_attendance_apply" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

<script>
  $(window).on('load',function(){ 
  // ブラウザバック時モーダルdismiss用URLの取得
  var @url = location.href;
  });
</script>