config/routes.rb
Rails.application.routes.draw do
  get 'requests/new'

  get 'offices/new'

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  # ログイン
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get 'attend_employees'
      get 'attendances/one_month_apply'
      patch 'attendances/update_one_month_apply'
      patch 'attendances/confirmation_one_month_apply'
      get 'attendances/edit_overtime_work_apply'
      patch 'attendances/update_overtime_work_apply'
      get 'attendances/recive_overtime_work_apply'
      patch 'attendances/confirmation_overtime_work_apply'
      get 'attendances/recive_change_attendance_apply'
      patch 'attendances/confirmation_change_attendance_apply'
      get 'attendances/edit_log'
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
    end
    collection do
      post 'import'
      resources :offices
    end
    resources :attendances, only: :update
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_user, only: %i(edit_one_month update_one_month update_one_month_apply one_month_apply confirmation_one_month_apply
                                    edit_overtime_work_apply update_overtime_work_apply recive_overtime_work_apply confirmation_overtime_work_apply
                                    recive_change_attendance_apply confirmation_change_attendance_apply edit_log)
  before_action :logged_in_user, only: %i(update edit_one_month update_one_month one_month_apply update_one_month_apply confirmation_one_month_apply
                                          edit_overtime_work_apply update_overtime_work_apply recive_overtime_work_apply confirmation_overtime_work_apply
                                          recive_change_attendance_apply confirmation_change_attendance_apply edit_log)
  before_action :superior_user, only: %i(one_month_apply confirmation_one_month_apply recive_overtime_work_apply confirmation_overtime_work_apply
                                        recive_change_attendance_apply confirmation_change_attendance_apply)
  before_action :correct_user, only: %i(update_one_month_apply edit_overtime_work_apply recive_overtime_work_apply confirmation_overtime_work_apply
                                        recive_change_attendance_apply confirmation_change_attendance_apply edit_log)
  before_action :admin_or_correct_user, only: %i(edit_one_month update_one_month)
  before_action :admin_exclusion, only: %i(update edit_one_monthupdate_one_month update_one_month_apply one_month_apply confirmation_one_month_apply
                                           edit_overtime_work_apply recive_overtime_work_apply confirmation_overtime_work_apply
                                           recive_change_attendance_apply confirmation_change_attendance_apply edit_log)
  before_action :set_one_month, only: %i(edit_one_month edit_overtime_work_apply recive_overtime_work_apply confirmation_overtime_work_apply
                                        recive_change_attendance_apply confirmation_change_attendance_apply edit_log)
  before_action :set_one_month_apply, only: %i(update_one_month_apply)

  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"
  INVALID_MSG = "無効な入力データがあった為、更新をキャンセルしました。"

  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current.change(sec: 0), changed_started_at: Time.current.change(sec: 0))
        flash[:info] = "おはようございます！"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes(finished_at: Time.current.change(sec: 0), changed_finished_at: Time.current.change(sec: 0))
        flash[:info] = "お疲れ様でした。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to @user
  end
  
  def edit_one_month
    @superiors = superior_without_me
  end
  
  def update_one_month
    ActiveRecord::Base.transaction do
      if attendances_invalid?
        attendances_params.each do |id, item|
          attendance = Attendance.find(id)
          if item[:change_superior_id].present?
            attendance.update_attributes!(item)
            attendance.update_attributes!(change_superior_name: User.find(item[:change_superior_id]).name)
          end
        end
        flash[:success] = "1ヶ月分の勤怠情報を更新しました。"
        redirect_to user_url(date: params[:date])
      else
        flash[:danger] = "#{INVALID_MSG}#{@msg}"
        redirect_to attendances_edit_one_month_user_url(date: params[:date])
      end
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = "#{INVALID_MSG}#{@msg}"
    redirect_to attendances_edit_one_month_user_url(date: params[:date])
  end

  def one_month_apply
    @users = month_applying_employee # 1ヶ月勤怠申請中の社員を@usersに代入
  end
  
  # 1ヶ月の勤怠申請提出
  def update_one_month_apply
    if selected_superior? # 申請先の上長が選択されているか？
      month_apply_params.each do |id, item|
        attendance = Attendance.find(id)
        attendance.update_attributes!(item)
        item[:superior_name] = User.find(item[:superior_id]).name
        attendance.update_attributes!(item)
        @month_apply = item[:month_apply].to_date.strftime("%-m")
        @superior = item[:superior_name]
      end
      flash[:success] = "#{@user.name}の#{@month_apply}月分勤怠申請を、#{@superior}へ提出しました。"
      redirect_to user_url(date: params[:date])
    else
      flash[:danger] = "申請先の上長を選択してください。"
      redirect_to user_url(date: params[:date])
    end
  end
  
  # 1ヶ月の勤怠申請承認
  def confirmation_one_month_apply
    confirmation_month_apply_params.each do |id, item|
      if apply_confirmed_invalid?(item[:status], item[:month_check])
        attendance = Attendance.find(id)
        attendance.update_attributes(item)
        if item[:status] == "否認"
          item[:month_approval] = 2
          item[:month_check] = "0"
          attendance.update_attributes(item)
        end
      end
    end
    flash[:success] = "1ヶ月勤怠申請の決裁を更新しました。"
    redirect_back(fallback_location: root_path) # 申請月のページにリダイレクト、エラーが出る前にroot_pathにとんでくれる。
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = "エラーが発生した為、1ヶ月勤怠申請の更新がキャンセルされました。"
    redirect_back(fallback_location: root_path)
  end
  
  # 残業申請提出ページ
  def edit_overtime_work_apply
    @superiors = superior_without_me
  end
  
  # 残業申請提出
  def update_overtime_work_apply
    overtime_work_apply_params.each do |id, item|
      if selected_overtime_superior?
        attendance = Attendance.find(id)
        attendance.update_attributes(item) unless time_select_invalid?(item)
        if attendance.next_day_check == "1"
          next_day_times(@user.designated_work_end_time, attendance.overtime_end_plan)
        else
          overwotking_times(@user.designated_work_end_time, attendance.overtime_end_plan)
        end
        attendance.update_attributes(overtime_hours: @total_time, overtime_superior_name: User.find(item[:overtime_superior_id]).name)
        flash[:success] = "#{attendance.overtime_superior_name}に残業申請を提出しました。"
        redirect_back(fallback_location: root_path)
      else
        msg_a = "申請先上長を選択してください。" if item[:overtime_superior_id].blank?
        msg_b = "業務処理内容を入力してください。" if item[:overtime_detail].blank?
        flash[:danger] = "#{msg_a}#{msg_b}"
        redirect_back(fallback_location: root_path)
      end
    end
  end
  
  # 残業申請確認ページ
  def recive_overtime_work_apply
    @users = overtime_applying_employee
  end
  
  # 残業申請承認
  def confirmation_overtime_work_apply
    confirmation_overtime_work_apply_params.each do |id, item|
      if apply_confirmed_invalid?(item[:overtime_status], item[:overtime_check])
        attendance = Attendance.find(id)
        attendance.update_attributes(item) unless time_select_invalid?(item)
        if item[:overtime_status] == "否認"
          item[:overtime_approval] = 2
          item[:overtime_check] = "0"
          attendance.update_attributes(item)
        end
      end
    end
    flash[:success] = "残業申請の決裁を更新しました。"
    redirect_to @user
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = "エラーが発生した為、残業申請の更新がキャンセルされました。"
    redirect_to root_path
  end
  
  # 勤怠変更確認ページ
  def recive_change_attendance_apply
    @users = change_applying_employee
  end
  
  # 勤怠変更承認
  def confirmation_change_attendance_apply
    ActiveRecord::Base.transaction do
      confirmation_attendances_params.each do |id, item|
        if apply_confirmed_invalid?(item[:change_status], item[:change_check])
          attendance = Attendance.find(id)
          item[:approval_date] = Time.current
          attendance.update_attributes(item)
          if item[:change_status] == "否認"
            item[:change_approval] = 2
            item[:change_check] = "0"
            item[:approval_date] = nil
            attendance.update_attributes(item)
          elsif item[:change_status] == "なし"
              item[:change_approval] = 1
              item[:change_check] = "0"
              item[:approval_date] = nil
              attendance.update_attributes(item)
          end
        end
      end
      flash[:success] = "勤怠変更の決裁を更新しました。"
      redirect_to user_url(date: params[:date])
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = "エラーが発生した為、勤怠変更の更新がキャンセルされました。"
    redirect_to root_path
  end
  
  def edit_log
    @superiors = change_superior
    
    # date_selectの選択年月範囲
    if Attendance.where(user_id: @user.id).where.not(calendar_day: nil).present?
      @start_year =  Attendance.where(user_id: @user.id).minimum(:calendar_day).year
      @end_year = Attendance.where(user_id: @user.id).maximum(:calendar_day).year
    end
    
    @logs =
    if params[:search].blank?
      Attendance.where(user_id: @user.id).where(worked_on: @first_day..@last_day).where(change_approval: 3).order(worked_on: "ASC")
    else
      search_years = ActiveSupport::HashWithIndifferentAccess.new(worked_on: params[:search]["worked_on(1i)"])
      search_months = ActiveSupport::HashWithIndifferentAccess.new(worked_on: params[:search]["worked_on(2i)"])
      @search_year = search_years[:worked_on]
      @search_month = search_months[:worked_on]
      Attendance.where(user_id: @user.id).search(params[:search]["worked_on(1i)"]).search(params[:search]["worked_on(2i)"]).where(change_approval: 3).order(worked_on: "ASC")
    end
  end
  
  private
    
    def attendances_params
      params.require(:user).permit(attendances: [:started_at, :finished_at, :changed_started_at, :changed_finished_at,
                                                 :note, :change_superior_id, :change_status, :change_check,
                                                 :change_approval, :change_next_day_check, :calendar_day])[:attendances]
    end
    
    # 勤怠変更申請承認
    def confirmation_attendances_params

app/helpers/attendances_helper.rb
module AttendancesHelper
  
  def attendance_attend(attendance)
    if Date.current == attendance.worked_on
      return '出社' if attendance.started_at.nil?
    end
    false
  end
  
  def attendance_leave(attendance)
    if Date.current == attendance.worked_on
      return '退社' if attendance.started_at.present? && attendance.finished_at.nil?
    end
    false
  end
  
  def attendances_invalid?
    attendances = true
    attendances_params.each do |id, item|
      if item[:change_superior_id].blank?
        next
      elsif item[:change_superior_id].present? && item[:note].blank?
        attendances = false
        if item[:note].blank?
          @msg = "備考を入力してください。"
        end
        break
      elsif item[:change_superior_id].present? && item[:note].present? && item['changed_started_at(4i)'] == "" && item['changed_started_at(5i)'] == "" && item['changed_finished_at(4i)'] == "" && item['changed_finished_at(5i)'] == ""
        attendances = false
        break
      elsif item[:change_superior_id].present? && item[:note].present? && item['changed_started_at(4i)'] == "" || item['changed_started_at(5i)'] == "" || item['changed_finished_at(4i)'] == "" || item['changed_finished_at(5i)'] == ""
        attendances = false
        break
      elsif item['changed_started_at(4i)'] > item['changed_finished_at(4i)'] && item[:change_next_day_check] == "0"
        attendances = false
        break
      elsif
        item['changed_started_at(4i)'] == item['changed_finished_at(4i)'] && item['changed_started_at(5i)'] > item['changed_finished_at(5i)'] && item[:change_next_day_check] == "0"
        attendances = false
        break
      end
    end
    return attendances
  end
  
  # 上長選択とtime_selectに任意の値が入力されていない場合の評価
  def time_select_invalid?(item)
    item[:change_superior_id].present? && item["started_at(4i)"] == "" && item["started_at(5i)"] == "" && item["finished_at(4i)"] == "" && item["finished_at(5i)"] == ""
  end
  
  # 本日の勤務中社員取得用
  def working_users
    User.where(id: Attendance.where.not(started_at: nil).
         where(id: Attendance.where(finished_at: nil)).
         where(id: Attendance.where(worked_on: Date.current)).select(:user_id))
  end
  
  # 1ヶ月の勤怠申請用
  def set_one_month_apply
    @user.attendances.where('worked_on >= ? and worked_on <= ?', @first_day, @last_day).order('worked_on')
  end
  
  # 1ヶ月勤怠申請中の社員を取得
  def month_applying_employee
    User.joins(:attendances).where.not(attendances: {superior_id: nil}).where(attendances: {month_approval: 2}).distinct
  end
  
  # 1ヶ月勤怠申請済の社員を取得
  def month_applicated_employee
    User.joins(:attendances).where.not(attendances: {superior_id: nil}).where(attendances: {month_approval: 3}).distinct
  end
  
  # 自分以外の上長
  def superior_without_me
    User.where(superior: true).where.not(id: current_user.id)
  end
  
  # 自分を含めたの上長
  def superior_add_me
    User.where(superior: true)
  end
  
  # 1ヶ月勤怠申請先の上長の選択されているか？
  def selected_superior?
    superior = true
    month_apply_params.each do |id, item|
      if item[:superior_id].blank? && [:month_apply].present?
        superior = false
      elsif item[:superior_id].present? && [:month_apply].present?
        superior = true
        break
      end
    end
    superior
  end
  
  # 1ヶ月勤怠申請が自分にきているか
  def has_month_apply
    User.joins(:attendances).where(attendances: {superior_id: current_user.id}).where(attendances: {status: "申請中"})
  end
  
  # 勤怠申請決裁の変更のチェックが入っているか？
  def apply_confirmed_invalid?(status, check)
    if (status == "承認" || status == "否認" || status == "なし")  && check == "1"
      confirmed = true
    else
      confirmed = false
    end
    confirmed
  end
  
  # 1ヶ月申請フォームのステータス表示
  def apply_status(status)
    case status
    when "申請中"
      "に申請中"
    when "承認"
      "から承認済"
    when "否認"
      "から否認"
    else
      "未"
    end
  end
  
  # 1ヶ月申請ボタンフォームのステータス表示
  def apply_btn_status(status)
    case status
    when "申請中"
      "申請先を変更"
    when "承認"
      "再申請"
    when "否認"
      "再申請"
    else
      "申請"
    end
  end


  # 残業申請先の上長の選択されているか？業務処理内容が入力されているか？
  def selected_overtime_superior?
    superior = true
    overtime_work_apply_params.each do |id, item|
      if item[:overtime_superior_id].blank? || item[:overtime_detail].blank?
        superior = false
      elsif item[:overtime_superior_id].present? && item[:overtime_detail].present?
        superior = true
        break
      end
    end
    superior
  end
  
  # 残業申請中の社員を取得
  def overtime_applying_employee
    User.joins(:attendances).where.not(attendances: {overtime_superior_id: nil}).where(attendances: {overtime_approval: 2}).distinct
  end
  
  def working_times(start, finish, next_day)
    if next_day == "1"
      # format("%.2f", (24 - ((start - finish) / 60) / 60.0))
      hour = (24 - start.hour) + finish.hour
      min = finish.min - start.min
      @total_time = hour + min / 60.00
    elsif
      # format("%.2f", (((finish - start) / 60) / 60.0))
      hour = finish.hour - start.hour
      min = finish.min - start.min
      @total_time = hour + min / 60.00
    end
  end
  
  # 残業申請時間外時間の計算
  def overwotking_times(basic, end_plan)
    hour = end_plan.hour - basic.hour
    min = end_plan.min - basic.min
    @total_time = hour + min / 60.00
  end
  
  # 翌日にまたがる残業申請時間外時間の計算
  def next_day_times(start, finish)
    hour = (24 - start.hour) + finish.hour
    min = finish.min - start.min
    @total_time = hour + min / 60.00
  end
  
  # 残業申請が自分にきているか
  def has_overtime_apply
    User.joins(:attendances).where(attendances: {overtime_superior_id: current_user.id}).where(attendances: {overtime_status: "申請中"})
  end
  
  # 残業申請のステータス表示
  def overtime_status_text(status)
    case status
    when "申請中"
      "　残業申請中"
    when "否認"
      "　残業否認"
    when "承認"
      "　残業承認"
    else
    end
  end
  
  # 勤怠変更申請中の社員を取得
  def change_applying_employee
    User.joins(:attendances).where.not(attendances: {change_superior_id: nil}).
                             where(attendances: {change_approval: 2}).distinct
  end
  
  # 勤怠変更申請が自分にきているか
  def has_change_apply
    User.joins(:attendances).where(attendances: {change_superior_id: current_user.id}).where(attendances: {change_status: "申請中"})
  end
  
  # 勤怠変更申請のステータス表示
  def change_status_text(status)
    case status
    when "申請中"
      "　勤怠編集申請中"
    when "否認"
      "　勤怠編集否認"
    when "承認"
      "　勤怠編集承認︎︎"
    when "なし"
    else
    end
  end
  
  # 勤怠ログの上長
  def change_superior
    User.where(superior: true)
  end
end

app/views/attendances/_one_month_apply.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-body">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><%= link_to "&times;".html_safe, "#{@url}" %></span>
      </button>
      <div class="row">
        <div class="col-md-12">
          <%= form_with(model: @user, url: attendances_confirmation_one_month_apply_user_path(@user), local: true, method: :patch) do |f| %>
            <% @users.each do |user| %>
                <% attendances = Attendance.where(user_id: user.id).where(status: "申請中") %>
                <% attendances.each do |attendance|%>
                  <% if attendance.month_apply.present? && attendance.superior_id == current_user.id && attendance.month_approval == 2 %>
                  <h3 class="center">【<%= user.name %>からの1ヶ月分の勤怠申請】</h3>
                  <table class="table table-condensed table-bordered table-hover">
                    <thead>
                      <tr>
                        <th class="center">月</th>
                        <th class="center">指示者確認<%= "\u329e" %></th>
                        <th class="center">変更</th>
                        <th class="center">勤怠を確認する</th>
                      </tr>
                    </thead>
                  <% break %>
                  <% end %>
                <% end %>

                <% attendances = Attendance.where(user_id: user.id).where(status: "申請中").merge(Attendance.order("attendances.worked_on DESC")) %>
                <% attendances.each do |attendance|%>
                  <% if attendance.month_apply.present? && attendance.superior_id == current_user.id && attendance.month_approval == 2 %>
                    <%= fields_for "attendances[]", attendance do |at|  %>
                      <tbody>
                        <tr>
                          <td class="center"><%= attendance.month_apply.strftime("%-m月") %></td>
                          <td class="center">
                            <%= at.select :status, ['なし', '申請中', '承認', '否認'], {}, class: "form-control" %>
                          </td>
                          <td class="center">
                            <%= at.check_box :month_check %>
                            <%= at.hidden_field :month_approval, value: 3 %>
                          </td>
                          <td class="center"><%= link_to "確認", user_path(id: user.id, date: attendance.month_apply), class: "btn btn-primary" %></td>
                        </tr>
                      </tbody>
                    <% end %>
                  <% end %>
              　<% end %>
            　</table>
            <% end %>

            <div class="center">
              <% if has_month_apply.count == 0 %>
                <h1>申請情報はありません。</h1>
              <% else %>
                <%= f.submit "変更を送信する", class: "btn btn-lg btn-primary" %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/attendances/_recive_change_attendance_apply.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-body">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <div class="row">
        <div class="col-md-12">
          <%= form_with(model: @user, url: attendances_confirmation_change_attendance_apply_user_path(date: @first_day), local: true, method: :patch) do |f| %> <!-- 1 -->
            <% @users.each do |user| %> <!-- 2 -->
              <% attendances = Attendance.where(user_id: user.id).where(change_approval: 2) %>
              <% attendances.each do |attendance| %> <!-- 3 -->
                <% if attendance.change_superior_id == current_user.id && attendance.change_approval == 2 %> <!-- 4 -->
                <h3 class="center">【<%= user.name %>からの勤怠変更申請】</h3>
                <table class="table table-condensed table-bordered table-hover">
                  <thead>
                    <tr>
                      <th class="center" rowspan="3">日付</th>
                      <th class="center" rowspan="3">曜日</th>
                      <th class="center" colspan="4">変更前</th>
                      <th class="center" colspan="4">変更後</th>
                      <th class="center" rowspan="3">備考</th>
                      <th class="center" rowspan="3">指示者確認<%= "\u329e" %></th>
                      <th class="center" rowspan="3">変更</th>
                      <th class="center" rowspan="3">勤怠を確認する</th>
                    </tr>
                    <tr>
                      <th class="center" colspan="2">出社</th>
                      <th class="center" colspan="2">退社</th>
                      <th class="center" colspan="2">出社</th>
                      <th class="center" colspan="2">退社</th>
                    </tr>
                    <tr>
                      <th class="center">時</th>
                      <th class="center">分</th>
                      <th class="center">時</th>
                      <th class="center">分</th>
                      <th class="center">時</th>
                      <th class="center">分</th>
                      <th class="center">時</th>
                      <th class="center">分</th>
                    </tr>
                  </thead>
                <% break %>
                <% end %> <!-- 4 -->
              <% end %> <!-- 3 -->
              
              <% attendances = Attendance.where(user_id: user.id).where(change_approval: 2).merge(Attendance.order("attendances.worked_on DESC")) %>
              <% attendances.each do |attendance| %> <!-- 5 -->
                <% if attendance.change_superior_id == current_user.id && attendance.change_approval == 2 %> <!-- 5.5 -->
                  <%= fields_for "attendances[]", attendance do |at| %> <!-- 6 -->
                    <tbody>
                      <tr>
                        <td class="center"><%= l(attendance.worked_on, format: :short) %></td>
                        <td class="center">
                          <% if attendance.worked_on.wday == 0 %>
                            <font color="#ff000">
                          <% elsif attendance.worked_on.wday == 6 %>
                            <font class="#0033cc">
                          <% end %>
                          <%= $days_of_the_week[attendance.worked_on.wday] %>
                        </td>
                        <td class="center"><%= attendance.started_at&.strftime("%-H") %></td>
                        <td class="center"><%= attendance.started_at&.floor_to(15.minutes)&.strftime("%-M") %></td>
                        <td class="center"><%= attendance.finished_at&.strftime("%-H") %></td>
                        <td class="center"><%= attendance.finished_at&.floor_to(15.minutes)&.strftime("%-M") %></td>
                        <td class="center"><%= attendance.changed_started_at&.strftime("%-H") %></td>
                        <td class="center"><%= attendance.changed_started_at&.floor_to(15.minutes)&.strftime("%-M") %></td>
                        <td class="center"><%= attendance.changed_finished_at&.strftime("%-H") %></td>
                        <td class="center"><%= attendance.changed_finished_at&.floor_to(15.minutes)&.strftime("%-M") %></td>
                        <td class="center"><%= attendance.note %></td>
                        <td class="center">
                          <%= at.select :change_status, ['なし','申請中', '承認', '否認'], {}, class: "form-control" %>
                        </td>
                        <td class="center">
                          <%= at.check_box :change_check %>
                          <%= at.hidden_field :change_approval, value: 3 %>
                        </td>
                        <td class="center"><%= link_to "確認", user_path(id: user.id, date: attendance.worked_on.beginning_of_month), class: "btn btn-lg btn-primary" %></td>
                      </tr>
                    </tbody>
                  <% end %> <!-- 6 -->
                <% end %> <!-- 5.5 -->
              <% end %> <!-- 5 -->
              </table>
            <% end %> <!-- 2 -->
            <div class="center">
              <% if has_change_apply.count == 0 %>
                <h1>申請情報はありません。</h1>
              <% else %>
                <%= f.submit "変更を送信する", class: "btn btn-lg btn-primary" %>
              <% end %>
            </div>
          <% end %> <!-- 1 -->
        </div>
      </div>
    </div>
  </div>
</div>

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>
<%= form_with(model: @user, url: attendances_update_one_month_user_path(date: @first_day), local: true, method: :patch) do |f| %>
<div>
  <h1>勤怠編集</h1>
  <table class="table table-bordered table-condensed table-striped table-hover" id="table-attendances">
    <thead>
      <tr>
        <th>日付</th>
        <th>曜日</th>
        <th>出社</th>
        <th>退社</th>
        <th>翌日</th>
        <th>在社時間</th>
        <th>備考</th>
        <th>指示者確認&#x329E;</th>
      </tr>
    </thead>
    <tbody>
      <% @attendances.each do |day| %>
        <%= f.fields_for "attendances[]", day do |attendance| %>
          <tr>
            <td><%= l(day.worked_on, format: :short) %></td>
            <td>
              <% if day.worked_on.wday == 0 %>
                <font color="#ff000">
              <% elsif day.worked_on.wday == 6 %>
                <font color="#0033cc">
              <% end %>
              <%= $days_of_the_week[day.worked_on.wday] %>
            </td>
            <% if Date.current <= day.worked_on && day.finished_at.blank? %>
              <td><%= attendance.time_select :changed_started_at, {include_blank: true}, disabled: true, class: "form-control bootstrap-date" %></td>
              <td><%= attendance.time_select :changed_finished_at, {include_blank: true}, disabled: true, class: "form-control bootstrap-date" %></td>
            <% else %>
              <td><%= attendance.time_select :changed_started_at, {include_blank: true}, class: "form-control bootstrap-date" %></td>
              <td><%= attendance.time_select :changed_finished_at,{include_blank: true}, class: "form-control bootstrap-date" %></td>
            <% end %>
            <td><%= attendance.check_box :change_next_day_check %></td>
            <td>
              <% if day.changed_started_at.present? && day.changed_finished_at.present? %>
                <%= format("%.2f", working_times(day.changed_started_at, day.changed_finished_at, day.change_next_day_check)) %>
              <% end %>
            </td>
            <td><%= attendance.text_field :note, placeholder: "入力必須", class: "form-control" %></td>
            <td>
              <% if Date.current <= day.worked_on && day.finished_at.blank? %>
                <%= attendance.collection_select :change_superior_id, @superiors, :id, :name,
                                                 {include_blank: true, selected: nil}, disabled: true, class: "form-control" %>
              <% else %>
                <%= attendance.collection_select :change_superior_id, @superiors, :id, :name,
                                                   {include_blank: true, selected: nil}, class: "form-control" %>
              <% end %>
              <%= attendance.hidden_field :change_status, value: "申請中" %>
              <%= attendance.hidden_field :change_approval, value: 2 %>
              <%= attendance.hidden_field :change_check, value: "0" %>
              <%= attendance.hidden_field :calendar_day, value: day.worked_on.to_date %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <div class="center">
    <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-primary" %>
    <%= f.submit "編集を保存する", class: "btn btn-lg btn-primary" %>
  </div>
</div>
<% end %>